Chore: introduce Fishery as object factory
grafana/synthetic-monitoring-app pull request #1023
Opened 2024-12-19 16:22 UTC by VikaCep

Ref: https://github.com/grafana/synthetic-monitoring-app/issues/850

This PR introduces Fishery to simplify mocking data in tests, eliminating the need to hard-code objects. It's paired with [Faker](https://github.com/faker-js/faker) to automatically generate test data for more dynamic and flexible testing scenarios.

It defines factories for
- All different check types
- Probes
- Check alerts

These factories are then used to create fixtures in `src/test/fixtures/probes.ts`, `src/test/fixtures/checks.ts`  and `src/test/fixtures/checkAlerts.ts`.

2025-01-10 10:25 UTC, ckbedwell requested changes
This is ace but there are some things we can tighten up! 🔧

2025-01-10 10:25 UTC, ckbedwell commented on src/test/db.ts
> +  id: faker.number.int({ min: 1, max: 999999 }),
Despite having the range very large, this is going to a potential source of flakiness in tests when IDs collide -- especially if we start creating larger data sets to test with.

Fishery provides a [sequence](https://github.com/thoughtbot/fishery?tab=readme-ov-file#define-and-use-factories) param that you can use as an ID to combat this problem but you'll have to change the factory to be a universal checks factory with a switch clause to the other factories.

2025-01-10 10:25 UTC, ckbedwell commented on src/test/db.ts
> +    id: faker.number.int({ min: 1, max: 999999 }),
Same case here (and probes) to use sequence instead.

2025-01-10 10:25 UTC, ckbedwell commented on src/test/fixtures/checkAlerts.ts
> +    db.alert.build({
If you offload the id to the Factory creating a sequence you could change this to something more succinct:

```
[
  CheckAlertType.HTTPRequestDurationTooHighP90,
  CheckAlertType.HTTPRequestDurationTooHighP95,
  CheckAlertType.HTTPTargetCertificateCloseToExpiring,
  CheckAlertType.ProbeFailedExecutionsTooHigh,
].map(name => db.alert.build({ name }))
```

2025-01-10 10:25 UTC, ckbedwell commented on src/test/fixtures/checks.ts
>    probes: [PRIVATE_PROBE.id, PUBLIC_PROBE.id] as number[],
Do we need to add any of these params if the Factory is making them all? (same with all the fixtures)

2025-01-10 10:25 UTC, ckbedwell commented on src/test/fixtures/probes.ts
>    public: false,
This seems like the only param we need as the factory is generating the params -- alternatively, or do we make a subclass to the probe factories so we have a PublicProbe factory and a PrivateProbe factory?

2025-01-10 10:25 UTC, ckbedwell commented on src/test/fixtures/probes.ts
>    online: false,
Same with these other fixtures, the only discerning param this probe needs is to be offline. Do we need the other params?

2025-01-10 10:26 UTC, ckbedwell commented on src/test/db.ts
> +    public: faker.datatype.boolean(),
As per my comment below on reflecting upon this, I think we should have two factories. One that creates public probes and one that creates private probes.

2025-01-10 21:47 UTC, VikaCep commented on src/test/fixtures/probes.ts
>    public: false,
Removed all unneeded params 👍

2025-01-14 21:12 UTC, VikaCep commented on src/test/db.ts
> +    public: faker.datatype.boolean(),
I tried creating two separate factories—one for PrivateProbes and one for PublicProbes—but since the IDs for public and private probes can’t overlap, we need to manage their creation within a single factory. This requires using a transient parameter, similar to how it’s done with checks. But having two separate factories was complicating things, so I found it more straightforward to just use one factory that creates private probes by default. For fixtures that require a public probe, we can simply set the `public: true` property.

2025-01-23 14:17 UTC, ckbedwell requested changes
One thing to change then let's get this in! 🎉

2025-01-23 14:17 UTC, ckbedwell commented on src/module.ts
> +}
Just needs a small modification so it gets tree-shaken properly and doesn't affect the production bundle size:

1. Move line 33 and associated imports to a file like `startServerWorker.ts`:

```
import { setupWorker } from 'msw';
import { handlers } from 'test/handlers';

setupWorker(...handlers).start();
```

2. change line 33 to: `await import(`./startServiceWorker`);`

Then we don't include the additional 850kb overhead our mocks have 😄 

![Comparing the webpack console output before and after making this change. Before 2.87MiB. After 2.02MiB](https://github.com/user-attachments/assets/93336939-9eba-47d6-8f5b-4e12b038e597)

2025-01-29 14:26 UTC, ckbedwell submitted a review, later dismissed
LGTM ❤️

2025-01-31 14:40 UTC, merged