Add oauth2 fields behind a feature flag
grafana/synthetic-monitoring-app pull request #609
Opened 2023-09-14 17:34 UTC by rdubrock

2023-10-20 14:11 UTC, ckbedwell requested changes
I assume the backend isn't set up for this yet as I could see it in the request but didn't return any of the options I had added.

I left a comment about what my expectation of the "Use Oauth2" checkbox should do after you untick it but when it is ticked my other expectation is that some of the fields should be required at that point but they can all be sent empty?
 
![Screenshot of Synthetic Monitoring plugin authentication accordion for http checks. The inputs are very  close to each other with not enough margin.](https://github.com/grafana/synthetic-monitoring-app/assets/6906380/320af709-a33b-43b4-8360-0c12c5e6c5d8)

The UI is pretty cramped, could do with a bit of margin-bottom to separate the forms from the tickboxes.

2023-10-20 14:11 UTC, ckbedwell commented on src/components/http/HttpSettings.tsx
> +                        console.log('appending scope');
Left in by mistake? 😃

2023-10-24 15:51 UTC, rdubrock commented
Yeah this one is in limbo and I've been meaning to come back to it when I carve out some time. The backend supports it but might require some changes, and I need a good test case

2024-03-28 21:51 UTC, rdubrock commented
Closing this for now, this got a little too stale

2024-03-28 21:51 UTC, closed without merging