chore: redesign landing page
grafana/synthetic-monitoring-app pull request #751
Opened 2024-04-12 20:08 UTC by rdubrock

![Screenshot 2024-04-12 at 12 08 31](https://github.com/grafana/synthetic-monitoring-app/assets/8377044/9514c617-bb46-4ece-826a-bf6fc886170a)

2024-04-19 14:18 UTC, roobre commented
Can't say much about the code, but I like the new look! 🎉

2024-04-19 15:00 UTC, ckbedwell requested changes
Few comments all very small. General ones:

1. Putting on my accessibility police hat, I don't like any of the min / max width properties on a few of the elements as they don't work great with responsiveness. You can definitely achieve what you want whilst making them respond when resolutions get smaller 😄 

2. Can we add some margin / padding to the bottom of the page? The code snippets has a bit but the images don't have, so that felt a bit weird as I was scrolling.

Otherwise, I think this is great. Good job! 💪

2024-04-19 15:27 UTC, ckbedwell commented on src/components/WelcomeTabs/WelcomeTabContent.tsx
> +          <img src={config.theme2.isDark ? privateProbeDark : privateProbeLight} className={styles.screenshot} />
🚨 Forgot to leave my other accessibility police comment: Alt text (for all the images), please 😄

2024-04-19 19:04 UTC, rdubrock commented on src/components/CodeSnippet/CodeSnippet.tsx
> +            {tabs.flatMap((tab) => {
Nope! This code changed a bunch and I forgot to update

2024-04-22 10:43 UTC, ckbedwell approved these changes
LGTM

2024-04-26 20:10 UTC, merged