feat: improve non-initialized pages
grafana/synthetic-monitoring-app pull request #839
Opened 2024-06-26 19:58 UTC by VikaCep

When the plugin is not initialized, we now display dedicated pages according to each route. 

![Screenshot 2024-06-26 at 15 19 27](https://github.com/grafana/synthetic-monitoring-app/assets/6271380/e85d8c3b-5ede-4269-94e2-b5fa96ad6a3e)
![Screenshot 2024-06-26 at 15 24 00](https://github.com/grafana/synthetic-monitoring-app/assets/6271380/bf1b7cb0-16e8-42dc-9d34-e3b87ab0a2a5)
![Screenshot 2024-06-26 at 16 58 04](https://github.com/grafana/synthetic-monitoring-app/assets/6271380/4a1a2886-9772-4bb2-ab98-53fbd9a7e035)

Fixes https://github.com/grafana/synthetic-monitoring-app/issues/807

2024-06-27 22:00 UTC, mem commented
This makes sense to me. Thanks!

I'll defer to someone else to do the actual review of the code.

2024-07-01 14:06 UTC, ckbedwell requested changes
A few very minor nitpicky things but otherwise this is ace! 👏 

I've noticed with my local set-up I have some buggyness with app initialisation that you get no UI feedback on but that can be addressed in a separate ticket which I'll expand upon.

I also noticed a bug with the native card component when there is no link provided which I'll also address in a separate PR shortly.

The main problem areas I spotted are on the Config page:

![Screenshot of Synthetic Monitoring plugin with the access token modal open, however the modal is empty of any content except a title that says 'Access Token'](https://github.com/grafana/synthetic-monitoring-app/assets/6906380/a9defa3f-2401-4dc2-9554-63377024fa97)

You can press the `Generate access token` button but the modal displays it as empty.

![Screenshot of Synthetic Monitoring plugin with the terraform config modal open. It shows an error at the top 'Cannot read properties of undefined (reading 'listProbes'). It also shows three code blocks. The bottom two related to importing existing checks and probes are empty.](https://github.com/grafana/synthetic-monitoring-app/assets/6906380/0582e16d-55cc-485b-be8d-3edcd82adb9b)

If I open the Terraform Config I get an error at the top and the existing code blocks are empty. I think we should hide these being displayed at all.

In regards to the tf.json code block, we should also make a note that they would need to initialize the plugin for it to work?

![Screenshot of the get started card for Alerts in Synthetic Monitoring on an ultra-wide monitor. The whole card stretches across the screen.](https://github.com/grafana/synthetic-monitoring-app/assets/6906380/40ac6cdf-0fac-4ef5-b820-55c03a52f7c3)

We should put a max-width on these cards, too.

![Screenshot of Synthetic Monitoring plugin on the checks page. It shows a subtitle under the title.](https://github.com/grafana/synthetic-monitoring-app/assets/6906380/32f4fca2-0975-4c46-81ab-b52d312ecbf2)

We should remove the subtitle on the checks page for consistency, too. None of the other pages show a subtitle.

2024-07-01 18:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/synthetic-monitoring-app?pullRequest=839) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/synthetic-monitoring-app?pullRequest=839) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/synthetic-monitoring-app?pullRequest=839) it.</sub>

2024-07-01 18:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/synthetic-monitoring-app?pullRequest=839) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/synthetic-monitoring-app?pullRequest=839) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/synthetic-monitoring-app?pullRequest=839) it.</sub>

2024-07-01 20:23 UTC, VikaCep commented on src/hooks/useAppInitializer.ts
> +export default useAppInitializer;
I agree with you, and great idea to enforce this in a eslint rule for consistency. Created a PR for that: https://github.com/grafana/synthetic-monitoring-app/pull/843

2024-07-02 15:29 UTC, ckbedwell approved these changes
LGTM 💪 🔥

2024-07-02 16:42 UTC, merged