fix: regression for longitude validation fix
grafana/synthetic-monitoring-app pull request #852
Opened 2024-07-03 21:29 UTC by VikaCep

Adds a regression test for the fix on longitude validation on creating new probes in https://github.com/grafana/synthetic-monitoring-app/pull/836

2024-07-03 21:43 UTC, mem approved these changes

2024-07-04 10:09 UTC, ckbedwell requested changes
Just a few suggestions but love that you've added this! 💪

2024-07-04 10:09 UTC, ckbedwell commented on src/page/NewProbe/NewProbe.test.tsx
> +  const errorMsg = await screen.queryByText('Longitude must be less than 180');
Tests for asserting when something _isn't present_ are really easily to accidentally end up with false positives (like when you accidentally completely break your validation so error messages never appear when they are supposed to...), so I like to either include in the test an assertion that the error validation appears correctly and then after fixing it the error leaves the DOM, or have an accompanying test which asserts for its presence:

```suggestion
  await user.type(longitudeInput, '180.01');
  await user.click(saveButton);

  const errorMsg = await screen.queryByText('Longitude must be less than 180');
  expect(errorMsg).toBeInTheDocument();

  await user.clear(longitudeInput);
  await user.type(longitudeInput, '116.3971');
```

2024-07-04 10:09 UTC, ckbedwell commented on src/page/NewProbe/NewProbe.test.tsx
> +  expect(expect(errorMsg).not.toBeInTheDocument());
```suggestion
  expect(errorMsg).not.toBeInTheDocument();
```

2024-07-04 15:19 UTC, ckbedwell approved these changes
🔥 🔥🔥

2024-07-04 15:33 UTC, merged