fix: prevent showing Edit Button when user is Viewer
grafana/synthetic-monitoring-app pull request #874
Opened 2024-07-19 21:52 UTC by VikaCep

Users with the role of `viewer` should be more restricted in what they can do/click in the app. 

For `viewer` users, this PR:
- Disables "Edit check" button in dashboards page
![image](https://github.com/user-attachments/assets/ca376ce0-36cf-4665-9d00-de0b071da346)
- Redirects the edit page route to home
- Redirects the config page to home
- Disables the "Populate default alerts", "Reset default alert rules" and "Save alerts" buttons in Alerting

Fixes https://github.com/grafana/support-escalations/issues/11601

2024-07-19 21:58 UTC, VikaCep commented
I still intend to add few more tests to improve coverage.

2024-07-22 09:05 UTC, ckbedwell requested changes
This is great, well done. I'm actually working on adding to this right now with RBAC but it will take longer to implement so this is a great solution 💪

2024-07-22 09:05 UTC, ckbedwell commented on src/page/CheckRouter.test.tsx
> +  });
We have a global afterEach set up in `test/jest-setup.tsx` that clears all mocks so you can remove these, too.

This is my bad, I'm going to make a ticket to document how our testing framework works and what assumptions and things it does for you out of the box to make tests clearer and more predictable to write 😅

2024-07-22 14:08 UTC, ckbedwell approved these changes
LGTM 🌟

2024-07-22 16:06 UTC, ckbedwell approved these changes
⭐

2024-07-22 16:08 UTC, merged