fix: update browser examples to use async check
grafana/synthetic-monitoring-app pull request #972
Opened 2024-10-16 19:29 UTC by VikaCep

Updates browser checks examples to use `async check` from `https://jslib.k6.io/k6-utils/1.5.0/index.js` as recommended in the [FAQ document](https://docs.google.com/document/d/1SbBdhYVGnEQ9XJe6DKYMErPI3O_E3anAp3Hdu_faUo8/edit#heading=h.duuadjcekgl6)

2024-10-18 15:45 UTC, ckbedwell requested changes
Just some thoughts! What do you think?

2024-10-18 15:45 UTC, ckbedwell commented on src/components/BrowserExamplesMenu/snippets/dispatch.js
> +    await check(ok, { "header": ok });
I think we should change some of these snippets to match the intent of the async/await so it is clearer what it is doing:

```
    await check(page.locator("h3"), {
      header: async (lo) => (await lo.textContent()) === "Contact us",
    })
```

2024-10-18 15:45 UTC, ckbedwell commented on src/components/BrowserExamplesMenu/snippets/getattribute.js
>      });
```
await check(page.locator("#dark-mode-toggle-3"), {
      "GetAttribute('mode')": async (lo) =>
        (await lo.getAttribute("mode")) === "light",
    })
    ```

2024-10-18 15:45 UTC, ckbedwell commented on src/components/BrowserExamplesMenu/snippets/querying.js
>      const titleWithXPath = await page.$(`//header//h1[@class="title"]`).then((e) => e.textContent());
Same here (and get rid of the `page.$` and replace with `page.locator`)

2024-10-18 15:45 UTC, ckbedwell commented on src/components/BrowserExamplesMenu/snippets/waitForFunction.js
>    }
Total side note but I hate [this waitForFunction example](https://grafana.com/docs/k6/latest/javascript-api/k6-browser/page/waitforfunction/) 😂 @ankur22 @inancgumus do we have a better example than this? It feels like it is giving mixed messages how to do page locators.

I like the [Playwright equivalent example](https://playwright.dev/docs/api/class-page#page-wait-for-function).

2024-10-18 18:04 UTC, VikaCep commented
Good points @ckbedwell, I changed the examples you mentioned as well as the the script we display when creating a new check 👍

2024-10-21 13:11 UTC, ckbedwell approved these changes
LGTM 🚀

2024-10-21 13:19 UTC, merged